apiVersion: v1
kind: Secret
metadata:
  name: quiz-app-secrets
  namespace: quiz-app
type: Opaque
data:
  # 'rootpassword' in base64
  mysql-root-password: cm9vdHBhc3N3b3Jk
  # 'quizpassword' in base64 (Ab bilkul correct hai!)
  db-password: cXVpenBhc3N3b3Jk
  # 'change-this-to-a-long-random-secret-key' in base64
  secret-key: Y2hhbmdlLXRoaXMtdG8tYS1sb25nLXJhbmRvbS1zZWNyZXQta2V5
